# Generated by Django 2.2.1 on 2019-05-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190525_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.Department'),
        ),
    ]
